###
GET http://localhost:4000/api/empleados
###
POST  http://localhost:4000/api/empleados
Content-Type: application/json

{
    "nombre": "leyva",
    "cargo" : "Developer",
    "office": "jun",
    "salario": "20000"
}

###
GET   http://localhost:4000/api/empleados/5fd27479ab25978d58197993

###
DELETE http://localhost:4000/api/empleados/5fd2d46e03348c2a20228677

###
put http://localhost:4000/api/empleados/5fd2d48d03348c2a20228678
Content-Type: application/json

{
    "salario":50000
}